


--1. Which channel is most frequently used for transaction?

SELECT Store_type, COUNT(*) AS TRAN_COUNT
FROM transactions
GROUP BY Store_type
ORDER BY TRAN_COUNT DESC

--2. What is the count of Male and female customer in database?
SELECT TOP 2 Gender, COUNT(Gender) AS NO_OF_CUSTOMER
FROM [dbo].[customer]
GROUP BY Gender
ORDER BY NO_OF_CUSTOMER DESC

--3.From which city do we have maximum number of customer and how many?

SELECT TOP 1 city_code, COUNT(*) AS TOTAL_CUS
FROM customer
GROUP BY city_code
ORDER BY TOTAL_CUS DESC

--4.How many sub-categories are there in book category?

SELECT prod_cat, COUNT(prod_subcat) AS NO_OF_CATEGORY
FROM [product category information]
WHERE prod_cat = 'Books'
GROUP BY prod_cat

--5.What is the maximum quantity of ptoducts ever ordered?

SELECT P.prod_cat,  MAX(Qty) AS MAX_QTY
FROM transactions AS T
JOIN [product category information] AS P
ON T.prod_cat_code = P.prod_cat_code
GROUP BY P.prod_cat

--6.What was the total revenue generated in categories Elecronic and Books?

SELECT  P.prod_cat, SUM(total_amt) AS total_amount
FROM transactions AS T
JOIN [product category information] AS P
ON T.prod_cat_code = P.prod_cat_code
WHERE P.prod_cat IN ('Electronics', 'Books')
GROUP BY P.prod_cat

--7.How many customer have >10 transaction with us, excluding returns

SELECT  C.customer_Id, COUNT(customer_Id) AS No_of_cust
FROM customer AS C
LEFT JOIN transactions AS T
ON C.customer_Id = T.cust_id
WHERE T.Qty > 0
GROUP BY customer_Id
HAVING COUNT(customer_Id) > 10

--8.What is the combine revenue from the "Electronics" and "Clothing" category, from "Flagship store"?

SELECT prod_cat, ROUND(SUM(t.total_amt),0) AS total_amount
FROM [product category information] AS P
JOIN transactions AS T
ON P.prod_sub_cat_code = T.prod_subcat_code
WHERE P.prod_cat IN ('Electronics', 'Clothing')
	AND T.Store_type = 'Flagship store'
GROUP BY prod_cat

--9.What is the total revenue generated from "Male" customer in "electronics" category? Output should display total revenue by product sub cat

SELECT P.prod_cat, P.prod_subcat, ROUND(SUM(total_amt),0) AS TOTAL_REVENUE
FROM transactions AS T
JOIN [product category information] AS P
ON T.prod_cat_code = P.prod_cat_code
	AND T.prod_subcat_code = P.prod_sub_cat_code
JOIN customer AS C
ON T.cust_id = C.customer_Id
WHERE C.Gender = 'M' AND P.prod_cat = 'Electronics'
GROUP BY P.prod_cat, P.prod_subcat
ORDER BY TOTAL_REVENUE DESC

--10.What is the percentage of sales and returns by product sub category; display only top 5 sub category in terms of sales

WITH subcat_summary AS 
	( SELECT p.prod_subcat, SUM(CASE WHEN Qty  > 0 THEN t.total_amt ELSE 0 END) AS sales_amt, 
		SUM(CASE WHEN t.Qty < 0 THEN ABS(t.total_amt) ELSE 0 END) AS return_amt
	FROM transactions AS t 
	JOIN [product category information] AS p 
	ON t.prod_subcat_code = p.prod_sub_cat_code AND t.prod_cat_code = p.prod_cat_code
		GROUP BY p.prod_subcat), 
	ranked AS ( SELECT TOP 5 prod_subcat, sales_amt, return_amt, (sales_amt + return_amt) AS total_amt 
	FROM subcat_summary 
	ORDER BY sales_amt DESC  )
SELECT prod_subcat, sales_amt, return_amt, 
	ROUND((sales_amt * 100.0) / (total_amt), 2) AS sales_percentage, 
	ROUND((return_amt * 100.0) / (total_amt), 2) AS return_percentage
FROM ranked

--11. For all customers aged between 25 to 35 years find what is the net total revenue 
--generated by these consumers in last 30 days of transactions from max transaction 
--date available in the data? 
WITH max_tran_date AS (
    SELECT MAX(CAST(tran_date AS DATE)) AS max_date
    FROM transactions
),
eligible_customers AS (
    SELECT c.customer_id
    FROM customer AS c
    CROSS JOIN max_tran_date AS m
    WHERE DATEDIFF(YEAR, CAST(c.dob AS DATE), m.max_date) BETWEEN 25 AND 35
)
SELECT ROUND(SUM(t.total_amt), 0) AS net_total_revenue
FROM transactions AS t
JOIN eligible_customers AS ec
  ON t.cust_id = ec.customer_id
JOIN max_tran_date m
  ON 1 = 1
WHERE CAST(t.tran_date AS DATE) >= DATEADD(DAY, -30, m.max_date)
  AND t.qty > 0;


--12.Which product category has seen the max value of returns in the last 3 months of transactions?
 
 SELECT TOP 1 p.prod_cat, 
	ROUND(SUM(ABS(t.total_amt)),0) AS return_value 
FROM transactions AS t 
JOIN [product category information] AS p 
ON t.prod_subcat_code = p.prod_sub_cat_code AND t.prod_cat_code = p.prod_cat_code 
WHERE t.qty < 0  AND t.tran_date >= DATEADD(MONTH, -3, (SELECT MAX(tran_date) FROM transactions))
GROUP BY p.prod_cat 
ORDER BY return_value DESC 

--13.Which store-type sells the maximum products; by value of sales amount and by quantity sold? 

SELECT store_type,
      ROUND(SUM(t.total_amt),0) AS total_sales_value,
       SUM(t.qty) AS total_quantity
FROM transactions t
WHERE t.qty > 0   -- exclude returns
GROUP BY store_type
ORDER BY total_sales_value DESC, total_quantity DESC


--14.What are the categories for which average revenue is above the overall average. 

WITH category_avg AS (
    SELECT p.prod_cat,
          ROUND(AVG(t.total_amt),0) AS avg_revenue
    FROM transactions AS t
    JOIN [product category information] AS p
      ON t.prod_subcat_code = p.prod_sub_cat_code
         AND t.prod_cat_code = p.prod_cat_code
    WHERE t.qty > 0
    GROUP BY p.prod_cat
),
overall_avg AS (
    SELECT ROUND(AVG(total_amt),0) AS overall_avg_revenue
    FROM transactions
    WHERE qty > 0
)
SELECT c.avg_revenue
FROM category_avg c, overall_avg o
WHERE c.avg_revenue > o.overall_avg_revenue
ORDER BY c.avg_revenue DESC;

--15. Find the average and total revenue by each subcategory for the categories which 
--are among top 5 categories in terms of quantity sold. 
WITH top5_categories AS (
    SELECT TOP 5 p.prod_cat
    FROM transactions t
    JOIN [product category information] p
      ON t.prod_subcat_code = p.prod_sub_cat_code
     AND t.prod_cat_code = p.prod_cat_code
    WHERE t.qty > 0
    GROUP BY p.prod_cat
    ORDER BY SUM(t.qty) DESC
)
SELECT p.prod_cat, p.prod_subcat,
       ROUND(SUM(t.total_amt),0) AS total_revenue,
       ROUND(AVG(t.total_amt),0) AS avg_revenue
FROM transactions t
JOIN [product category information] p
  ON t.prod_subcat_code = p.prod_sub_cat_code
 AND t.prod_cat_code = p.prod_cat_code
WHERE t.qty > 0
  AND p.prod_cat IN (SELECT prod_cat FROM top5_categories)
GROUP BY p.prod_cat, p.prod_subcat
ORDER BY p.prod_cat, total_revenue DESC;




